export const ITEM_STAT_TEXT: Record<string, string> = {
  "인스트럭터": "ATK x 1.5",
  "실버 EXP": "ATK x 1.6",
  "실버 BAL": "ATK x 1.8",
  "실버 QUICK": "ATK x 1.7 / TP +20",
  "실버 PLUS": "ATK x 1.9 / LP +20",
  "골드 슬라이서": "ATK x 2",
  "골드 EXP": "ATK x 2.1",
  "골드 CON": "ATK x 2.2 / LP -20",
  "골드 BAL": "ATK x 2.3 / DEF +20",
  "빅 슬라이서": "ATK x 2.5",
  "빅 QUICK": "ATK x 2.5 / TP +20",
  "빅 DEF": "ATK x 2.5 / DEF +20",
  "빅 BAL": "ATK x 2.6",
  "위너 슬라이서": "ATK x 2.7",
  "위너 BAL": "ATK x 2.8",
  "위너 PLUS": "ATK x 2.7 / LP +20",
  "위너 EXP": "ATK x 2.8",
  "그레이트 원": "ATK x 3",
  "스페이스 리퍼": "ATK x 3 / TP +10",
  "펠레의 빙검": "ATK x 3 / DEF +20",
  "맘모스": "ATK x 3.1 / DEF +20",
  "트윌라잇 크로스": "ATK x 3.3 / TP +20",
  "수련검": "ATK x 1.5",
  "키퍼": "ATK x 1.8",
  "블리츠": "ATK x 2",
  "플리커": "ATK x 2.2",
  "가디안": "ATK x 2.3 / LP +20",
  "장검": "ATK x 2.5 / DEX +20",
  "드래곤스네일": "ATK x 2.5 / LP +10 / DEF +20",
  "씨즈": "ATK x 2.6 / LP +20 / DEX -20",
  "로프란트 글로리": "ATK x 2.8 / LP +30",
  "멸살지옥검": "ATK x 3.4",
  "어씨스터": "ATK x 1.5",
  "듀얼 레이지": "ATK x 1.7",
  "굿 펠라스": "ATK x 2",
  "길라디움 DX": "ATK x 2.4 / TP +20",
  "길라디움 RX": "ATK x 2.4 / TP +20",
  "트윈 블래스터": "ATK x 2.7",
  "가르시아 커스텀": "ATK x 2.8 / DEF +10 / DEX +10",
  "리볼버 발렌타인": "ATK x 2.9 / DEX +30",
  "더 레이지": "ATK x 3.1",
  "블루": "ATK x 1.5",
  "튜터": "ATK x 1.8",
  "토르트": "ATK x 1.9",
  "레토르트": "ATK x 2",
  "T-써클렛": "ATK x 2.1 / TP +20",
  "S-써클렛": "ATK x 2.2",
  "가리우스": "ATK x 2.3",
  "토르": "ATK x 2.35",
  "아이리스 써클렛": "ATK x 2.35",
  "G-써클렛": "ATK x 2.4 / DEF +20",
  "천원": "ATK x 2.5",
  "멜리사의 해골": "ATK x 2.9",
  "바인드 프리즘": "ATK x 2.9",
  "크림슨 프리즘": "ATK x 2.9",
  "헬 프리즘": "ATK x 3",
  "악마의 문장": "ATK x 3.2",
  "마일드 스모크": "ATK x 1.5",
  "쵸이스": "ATK x 1.8",
  "헤비 원": "ATK x 2.2",
  "헤이즐 스모크": "ATK x 2.4 / DEX +20",
  "시가보르도": "ATK x 2.55 / DEX +30",
  "체인지 스모크": "ATK x 2.6",
  "체인지 스모커": "ATK x 2.6",
  "후버의 자존심": "ATK x 2.7 / TP +20",
  "군터의 팔": "ATK x 3",
  "글래스 렌즈": "ATK x 1.5",
  "옵틱 써클": "ATK x 1.8",
  "프라임 렌즈": "ATK x 2.1",
  "언터처블 렌즈": "ATK x 2.5 / DEX +30",
  "타이거 아이": "ATK x 3",
  "큐티 스톤": "ATK x 2",
  "오르딘 핑거": "ATK x 2 / TP +10 / LP +10 / DEX +10",
  "라이언 하트": "ATK x 2.2",
  "비아트리노": "ATK x 2.3 / LP +10",
  "소울 브레이커": "ATK x 2.4",
  "리바이어든": "ATK x 2.5 / LP +10 / DEP +20",
  "어비스 블랙": "ATK x 2.6",
  "발뭉": "ATK x 3.2",
  "옐로 리본": "ATK x 1.5",
  "블루 리본": "ATK x 1.8",
  "화이트 리본": "ATK x 2",
  "레드 리본": "ATK x 2.2",
  "실버 리본": "ATK x 2.4 / DEF +10",
  "골드 리본": "ATK x 2.6 / DEX +20",
  "네리사의 마음": "ATK x 2.6 / DEF +30",
  "레인보우 리본": "ATK x 2.75",
  "플라티늄 리본": "ATK x 2.8",
  "젤 샤프란": "ATK x 3",
  "베이직 크로": "ATK x 1.7",
  "캐츠 시저": "ATK x 1.9",
  "세라믹 크로": "ATK x 2.2",
  "이글 네일": "ATK x 2.4 / DEF +20",
  "아이언 크로": "ATK x 2.6",
  "크리스탈 크로": "ATK x 2.9 / TP +20",
  "여인의 키스": "ATK x 3.2",
  "B-포트": "ATK x 1.5",
  "아이비 포트": "ATK x 1.7",
  "스파이더 포트": "ATK x 1.9",
  "스네이크 포트": "ATK x 2.2",
  "해저드 포트": "ATK x 2.5",
  "스노우 화이트": "ATK x 3",
  "베이직 휠": "ATK x 1.7",
  "체리오트": "ATK x 2",
  "써니 휠": "ATK x 2.3",
  "파이어 휠": "ATK x 2.5",
  "쥬다스 요요": "ATK x 3",
  "바운서": "HP x 2",
  "바운서 EXP": "HP x 2",
  "바운서 BAL": "HP x 2.1",
  "레더 아머": "HP x 2.1",
  "세라믹 아머": "HP x 2.4",
  "클래식 아머": "HP x 2.7 / TP -10",
  "클래식 EXP": "HP x 2.8",
  "클래식 PLUS": "HP x 2.9",
  "애쓸릿 러버": "HP x 2.8",
  "파워 아머": "HP x 2.8",
  "파워 EXP": "HP x 2.9",
  "엘린듐 아머": "HP x 3",
  "크로슬리 페일러": "HP x 3.1",
  "아크 아머": "HP x 3.2",
  "아크론 아머": "HP x 3.4",
  "그라톡스": "DEX +50",
  "천신경": "DEX +60 / TP +15",
  "미라쥐": "DEX +70 / DEF +10",
  "프라임 블레스": "DEX +100 / DEF +15",
  "천사의 선물": "DEX +150",
  "금반지": "경험치 증가 없음",
  "루비반지": "경험치 증가 없음",
  "다이아반지": "TP + 20 / 경험치 증가 없음",
  "램버트의 반지": "경험치 증가 없음",
  "코어반지": "경험치 증가 없음",
  "가죽 벨트": "DEF +30",
  "체인 벨트": "DEF +45",
  "아이언 벨트": "DEF +55",
  "램버트의 벨트": "DEF +80",
  "제쿨트 벨트": "DEF +100 / DEX +20",
  "스톤의 벨트": "DEF +150",
  "등산화": "TP +10",
  "군화": "TP +20 / PSY +10",
  "파워드 슈즈": "TP +40",
  "램버트의 슈즈": "TP +50",
  "라이트닝 슈즈": "TP +60 / DEX +20",
  "영자 신발": "TP +80",
  "안정제": "상태 이상 해제",
  "완전회복캡슐": "모든 체력 회복",
  "여신의 성수": "모든 체력 회복 / 상태 이상 해제",
  "라이징 스톰": "자기장의 폭풍 지대",
  "파멸의 폭염1": "상태이상 - 화상",
  "파멸의 폭염2": "상태이상 - 화상",
  "애스트로 범": "메테오"
};

const normalizedItemStatText = new Map(
  Object.entries(ITEM_STAT_TEXT).map(([name, stats]) => [normalizeItemName(name), stats])
);

export function getItemStatText(name: string): string | undefined {
  return ITEM_STAT_TEXT[name] ?? normalizedItemStatText.get(normalizeItemName(name));
}

function normalizeItemName(name: string): string {
  return name.replace(/[\s.]/g, "").toLowerCase();
}
